# Generated by Django 4.2.7 on 2024-06-28 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0068_product_date_create_product_date_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название перевозчика')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(max_length=100, verbose_name='Номер отправления')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Вес, кг.')),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=100, verbose_name='Объем')),
                ('tariff', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость доставки $')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость товаров в заказах ¥')),
                ('delivery', models.CharField(choices=[('Авто', 'Авто'), ('Авто-экспресс', 'Авто-экспресс'), ('Жд', 'Жд'), ('Авиа', 'Авиа')], default='Авто', max_length=100, verbose_name='Тип отправления')),
                ('places', models.IntegerField(default=1, verbose_name='Количество мест')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('first_step', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('second_step', models.BooleanField(default=False, verbose_name='В Москве')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier', to='sendings.carriers', verbose_name='Перевозчик')),
                ('logistics', models.ManyToManyField(related_name='sendings', to='core.logistics', verbose_name='Грузы')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-id'],
            },
        ),

    ]
