# Generated by Django 4.2.6 on 2023-10-29 17:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clients_date_create_clients_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
