# Generated by Django 4.2.6 on 2023-10-31 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_clients_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Товар')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка на товар')),
                ('arrive', models.BooleanField(verbose_name='Прибыл на склад')),
                ('paid', models.BooleanField(verbose_name='Оплачен')),
                ('photo', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrive_price',
            field=models.FloatField(verbose_name='Цена доставки $'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_for_client',
            field=models.FloatField(verbose_name='Курс юаня для клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_for_company',
            field=models.FloatField(verbose_name='Курс юаня для компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marker',
            field=models.CharField(max_length=100, verbose_name='Маркировка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформление', 'Оформление'), ('На оплату', 'Оплата'), ('Завершен', 'Выполнен')], default='re', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(verbose_name='Вес кг.'),
        ),
        migrations.AddField(
            model_name='order',
            name='publications',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
