# Generated by Django 4.2.6 on 2023-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_alter_clients_date_create_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='publications',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='core.product', verbose_name='Товары'),
        ),
    ]
