# Generated by Django 4.2.6 on 2023-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='marker',
            field=models.CharField(max_length=100, unique=True, verbose_name='Маркировка'),
        ),
    ]
