# Generated by Django 4.2.7 on 2023-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clients_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
