# Generated by Django 4.2.7 on 2023-11-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='draft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость доставки по Китаю'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrive_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена доставки $'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_for_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Курс юаня для клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_for_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Курс юаня для компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='marker',
            field=models.CharField(max_length=100, verbose_name='Маркировка'),
        ),
    ]
