# Generated by Django 4.2.7 on 2023-11-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_full_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='draft',
            new_name='fraht',
        ),
    ]
