# Generated by Django 4.2.7 on 2023-11-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_draft_product_fraht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=500, verbose_name='Ссылка на продавца'),
        ),
    ]
