# Generated by Django 4.2.7 on 2023-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена ₽'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_for_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Курс ¥ для клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_for_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Курс ¥ для компании'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена ¥'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='core/image', verbose_name='Изображение'),
        ),
    ]
