# Generated by Django 4.2.7 on 2024-02-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_product_fraht_alter_product_full_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Высота')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Ширина')),
                ('lenght', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Длина')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Вес')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Объем')),
                ('density', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Плотность')),
                ('package', models.CharField(choices=[('simply', 'Простая'), ('sheathing', 'Обрешетка'), ('box', 'Ящик')], default='simply', max_length=100, verbose_name='Упаковка')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость')),
                ('delivery', models.CharField(choices=[('undelivered', 'Не доставлено'), ('in_stock', 'На складе Китай'), ('in_moscow', 'В Москве'), ('delivered', 'Доставлено')], default='undelivered', max_length=100, verbose_name='Статус отправления')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-id'],
            },
        ),
    ]
