# Generated by Django 4.2.7 on 2024-02-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Страховка'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Тариф'),
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='order',
        ),
        migrations.AlterField(
            model_name='logistics',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Общая стоимость'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='order',
            field=models.ManyToManyField(related_name='delivery', to='core.order', verbose_name='Заказ'),
        ),
    ]
