# Generated by Django 4.2.7 on 2024-02-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_logistics_insurance_logistics_tariff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='price',
            new_name='full_price',
        ),
        migrations.AddField(
            model_name='logistics',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость упаковки'),
        ),
    ]
