# Generated by Django 4.2.7 on 2024-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_price_logistics_full_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Высота, см.'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='lenght',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Длина, см.'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='package',
            field=models.CharField(choices=[('Простая', 'Простая'), ('Обрешетка', 'Обрешетка'), ('Ящик', 'Ящик')], default='simply', max_length=100, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Вес, кг.'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Ширина, см.'),
        ),
    ]
