# Generated by Django 4.2.7 on 2024-02-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_logistics_height_alter_logistics_lenght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrive_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AddField(
            model_name='clients',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Счет'),
        ),
        migrations.AddField(
            model_name='logistics',
            name='order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость товаров в заказах'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформление', 'Оформление'), ('На оплату', 'Оплата'), ('Завершен', 'Выполнен')], default='Оформление', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество мест'),
        ),
    ]
