# Generated by Django 4.2.7 on 2024-02-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_logistics_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
