# Generated by Django 4.2.7 on 2024-02-28 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='marker',
            field=models.CharField(max_length=100, null=True, verbose_name='Маркировка груза'),
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='order',
            name='marker',
            field=models.CharField(max_length=100, verbose_name='Маркировка заказа'),
        ),
    ]
