# Generated by Django 4.2.7 on 2024-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_logistics_marker_alter_imagesproduct_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='marker',
            field=models.CharField(max_length=100, verbose_name='Маркировка груза'),
        ),
    ]
