# Generated by Django 4.2.7 on 2024-02-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_logistics_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='order',
        ),
        migrations.AddField(
            model_name='logistics',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='core.product', verbose_name='Товары'),
        ),
    ]
