# Generated by Django 4.2.7 on 2024-02-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_logistics_order_logistics_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='order',
            new_name='products',
        ),
    ]
