# Generated by Django 4.2.7 on 2024-03-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_logistics_products_product_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to='core.logistics', verbose_name='Доставка'),
        ),
    ]
