# Generated by Django 4.2.7 on 2024-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_logistics_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
