# Generated by Django 4.2.7 on 2024-03-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_logistics_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivers', to='core.logistics', verbose_name='Доставка'),
        ),
    ]
