# Generated by Django 4.2.7 on 2024-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_product_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logistics',
        ),
        migrations.AddField(
            model_name='logistics',
            name='product',
            field=models.ManyToManyField(to='core.product', verbose_name='Товары'),
        ),
    ]
