# Generated by Django 4.2.7 on 2024-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_product_logistics_logistics_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='product',
            field=models.ManyToManyField(related_name='logistics', to='core.product', verbose_name='Товары'),
        ),
    ]
