# Generated by Django 4.2.7 on 2024-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_logistics_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marker',
            field=models.CharField(max_length=100, null=True, verbose_name='маркировка товара'),
        ),
    ]
