# Generated by Django 4.2.7 on 2024-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_product_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Наценка ¥'),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Прибыль'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Наценка ¥'),
        ),
    ]
