# Generated by Django 4.2.7 on 2024-03-24 16:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_marker_product_product_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='delivery',
            field=models.CharField(choices=[('undelivered', 'Не отправлено'), ('arrived', 'Отправлено'), ('in_moscow', 'В Москве'), ('delivered', 'Доставлено клиенту')], default='undelivered', max_length=100, verbose_name='Статус отправления'),
        ),
    ]
