# Generated by Django 4.2.7 on 2024-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_margin_product_margin_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_order',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(null=True, to='core.product', verbose_name='Товары'),
        ),
    ]
