# Generated by Django 4.2.7 on 2024-04-03 16:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_order_number_order_product_number_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='messanger',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='core.product', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на продавца'),
        ),
    ]
