# Generated by Django 4.2.7 on 2024-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_clients_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fraht_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Доставка по Китаю для компании ¥'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена для компании ¥'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Доставка по Китаю для клиента ¥'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена для клиента ¥'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
