# Generated by Django 4.2.7 on 2024-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_product_fraht_company_product_price_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена для компании ¥'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_rub_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена для компании ₽'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_price_company',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Общая цена для компании ¥'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена для клиента ¥'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Итоговая цена для клиента ₽'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Общая цена для клиента ¥'),
        ),
    ]
