# Generated by Django 4.2.7 on 2024-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_order_paid_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='delivery',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Авто-экспресс', 'Авто-экспресс'), ('Жд', 'Жд'), ('Авиа', 'Авиа')], default='Авто', max_length=100, verbose_name='Тип отправления'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='package',
            field=models.CharField(choices=[('Простая', 'Простая'), ('Скотч-мешок-скотч', 'Скотч-мешок-скотч'), ('Обрешетка', 'Обрешетка'), ('Ящик', 'Ящик')], default='simply', max_length=100, verbose_name='Упаковка'),
        ),
    ]
