# Generated by Django 4.2.7 on 2024-04-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_logistics_delivery_alter_logistics_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproduct',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product'),
        ),
    ]
