# Generated by Django 4.2.7 on 2024-04-23 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_logistics_first_step_logistics_second_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logistic_images/', validators=[django.core.validators.validate_image_file_extension])),
                ('logistic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logistic_images', to='core.logistics')),
            ],
            options={
                'verbose_name': 'Изображение упакованного груза',
                'verbose_name_plural': 'Изображения упакованного груза',
                'ordering': ['-id'],
            },
        ),
    ]
