# Generated by Django 4.2.7 on 2024-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_imageslogistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='places',
            field=models.IntegerField(default=1, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость страховки $'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость упаковки $'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость доставки $'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оформление', 'Оформление'), ('Ожидает отправки', 'Ожидает отправки'), ('Завершен', 'Выполнен')], default='Оформление', max_length=100, verbose_name='Статус'),
        ),
    ]
