# Generated by Django 4.2.7 on 2024-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_logistics_extra_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order', to='core.product', verbose_name='Товары'),
        ),
    ]
