# Generated by Django 4.2.7 on 2024-05-03 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0060_logistics_owner_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_method',
            field=models.CharField(choices=[('Альфа-банк', 'Альфа-банк Игорь'), ('Сбер', 'Сбер Мария'), ('Тинькофф', 'Тинькофф Игорь'), ('Тимофеев', 'Тимофеев'), ('Наличные', 'Наличные'), ('Расчетный счет', 'Расчетный счет(ИП)')], default='Наличные', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
