# Generated by Django 4.2.7 on 2024-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_account_user_alter_order_paid_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='takemoney',
            field=models.CharField(blank=True, choices=[('Игорь Смирнов', 'Игорь Смирнов'), ('Сергей Тимофеев', 'Сергей Тимофеев'), ('Мария', 'Мария')], max_length=100, verbose_name='Кто принял оплату'),
        ),
    ]
