# Generated by Django 4.2.7 on 2024-05-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_notesproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_notes', to='core.product', verbose_name='Товар'),
        ),
    ]
