# Generated by Django 4.2.7 on 2024-07-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='tariff_one_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость доставки за 1кг. $'),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость доставки общая $'),
        ),
    ]
