# Generated by Django 4.2.7 on 2024-07-19 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0072_filesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший'),
        ),
    ]
