# Generated by Django 4.2.7 on 2024-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_notification_readed'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='company_delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='себестоимость(Доставка/упаковка/страховка) $'),
        ),
    ]
