# Generated by Django 4.2.7 on 2024-07-31 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0077_logistics_company_delivery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.ManyToManyField(null=True, related_name='notifications', to='core.notification', verbose_name='Уведомления')),
                ('readers', models.ManyToManyField(null=True, related_name='readers', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
        ),
    ]
