# Generated by Django 4.2.7 on 2024-07-31 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0078_readnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnotification',
            name='notifications',
            field=models.ManyToManyField(related_name='notifications', to='core.notification', verbose_name='Уведомления'),
        ),
        migrations.AlterField(
            model_name='readnotification',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
