# Generated by Django 4.2.7 on 2024-07-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_readnotification_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnotification',
            name='notifications',
        ),
        migrations.AddField(
            model_name='readnotification',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.notification', verbose_name='Уведомления'),
        ),
    ]
