# Generated by Django 4.2.7 on 2024-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_readnotification_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Примечание по заказу'),
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Примечание по товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_order',
            field=models.CharField(blank=True, max_length=400, verbose_name='Номер заказа'),
        ),
    ]
