# Generated by Django 4.2.7 on 2024-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_order_comment_product_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spendings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Стоимость')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
    ]
