# Generated by Django 4.2.7 on 2024-08-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_spendings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendings',
            options={'ordering': ['-date_create'], 'verbose_name': 'Затрата', 'verbose_name_plural': 'Затраты'},
        ),
    ]
