# Generated by Django 4.2.7 on 2024-08-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_spendings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/invoices')),
                ('logistic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.logistics')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-id'],
            },
        ),
    ]
