# Generated by Django 4.2.7 on 2024-08-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_invoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='logistic',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.logistics'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_method',
            field=models.CharField(choices=[('Альфа-банк', 'Альфа-банк Игорь'), ('Сбер', 'Сбер Мария'), ('Тинькофф', 'Тинькофф Игорь'), ('Тимофеев', 'Тимофеев'), ('Наличные', 'Наличные'), ('Расчетный счет', 'Расчетный счет(ИП)'), ('Игорь', 'Игорь')], default='Наличные', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
