# Generated by Django 4.2.7 on 2024-09-16 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_invoices_logistic_alter_order_paid_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='core.clients', verbose_name='Клиент'),
        ),
    ]
